# Generated by Django 6.0.6 on 2026-06-07 15:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quota_limit', models.PositiveIntegerField(help_text='Maximum allowed quota')),
                ('price_in_cents', models.PositiveIntegerField(default=0, help_text='Price in cents')),
                ('is_active', models.BooleanField(default=True)),
                ('duration_days', models.PositiveIntegerField(default=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='quota_used',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Cancelled'), ('expired', 'Expried'), ('past_due', 'Pas due')], default='active', max_length=20)),
                ('quota_used', models.PositiveIntegerField(default=0)),
                ('activated_at', models.DateField(auto_now_add=True)),
                ('current_period_start', models.DateField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateField()),
                ('canceled_at', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='diagnostic.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'plan'), name='unique_active_subscription_per_plan')],
            },
        ),
    ]
