# Generated by Django 6.0.6 on 2026-06-08 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0002_plan_remove_user_quota_used_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plant_type', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('exposure', models.CharField(choices=[('full_sun', 'Full sun'), ('partial_shade', 'Partial shade'), ('full_shade', 'Full shade'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('soil_type', models.CharField(choices=[('clay', 'clay'), ('sandy', 'sandy'), ('loamy', 'loamy'), ('chalky', 'chalky'), ('unknown', 'unknown')], default='unknown', max_length=20)),
                ('image', models.ImageField(upload_to='plant_submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
