# Generated by Django 6.0.6 on 2026-06-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0003_plantsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantsubmission',
            name='plant_type',
            field=models.CharField(blank=True, choices=[('apple', 'Apple'), ('potato', 'Potato'), ('tomato', 'Tomato')], max_length=255, null=True),
        ),
    ]
