# Generated by Django 6.0.6 on 2026-06-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0004_alter_plantsubmission_plant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantsubmission',
            name='exposure',
            field=models.CharField(blank=True, choices=[('full_sun', 'Full sun'), ('partial_shade', 'Partial shade'), ('full_shade', 'Full shade')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plantsubmission',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('clay', 'clay'), ('sandy', 'sandy'), ('loamy', 'loamy'), ('chalky', 'chalky')], max_length=20, null=True),
        ),
    ]
