# Generated by Django 6.0.6 on 2026-06-08 20:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0005_alter_plantsubmission_exposure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(blank=True, choices=[('apple', 'Apple'), ('potato', 'Potato'), ('tomato', 'Tomato')], max_length=255, null=True)),
                ('disease_label', models.CharField(choices=[('healthy', 'Healthy'), ('early_blight', 'Early Blight')], max_length=255)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=50)),
                ('exposure', models.CharField(blank=True, choices=[('full_sun', 'Full sun'), ('partial_shade', 'Partial shade'), ('full_shade', 'Full shade')], max_length=20, null=True)),
                ('soil_type', models.CharField(blank=True, choices=[('clay', 'clay'), ('sandy', 'sandy'), ('loamy', 'loamy'), ('chalky', 'chalky')], max_length=20, null=True)),
                ('advice_text', models.TextField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plant_type', 'disease_label', 'severity', 'soil_type', 'exposure'), name='unique_advice_rule')],
            },
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('low_confidence', 'Low confidence'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('detected_plant', models.CharField(blank=True, choices=[('apple', 'Apple'), ('potato', 'Potato'), ('tomato', 'Tomato')], max_length=255, null=True)),
                ('plant_confidence', models.FloatField(blank=True, null=True)),
                ('detected_disease', models.CharField(blank=True, choices=[('healthy', 'Healthy'), ('early_blight', 'Early Blight')], max_length=255, null=True)),
                ('disease_confidence', models.FloatField(blank=True, null=True)),
                ('advice_text', models.TextField(blank=True, null=True)),
                ('raw_model_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advice_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostics', to='diagnostic.advicerule')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic', to='diagnostic.plantsubmission')),
            ],
        ),
    ]
