# Generated by Django 6.0.6 on 2026-06-09 09:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0006_advicerule_diagnostic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advicerule',
            name='disease_label',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('early_blight', 'Early Blight'), ('late_blight', 'Late Blight')], max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='detected_disease',
            field=models.CharField(blank=True, choices=[('healthy', 'Healthy'), ('early_blight', 'Early Blight'), ('late_blight', 'Late Blight')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('submission_created', 'Submission created'), ('diagnostic_success', 'Diagnostic success'), ('diagnostic_failed', 'Diagnostic failed'), ('subscription_created', 'Subscription created'), ('subscription_expired', 'Subscription expired'), ('subscription_canceled', 'Subscription canceled')], max_length=50)),
                ('ip_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
