# Generated by Django 6.0.6 on 2026-06-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0008_user_token_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostic',
            name='disease_confidence',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='plant_confidence',
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
