# Generated by Django 6.0.6 on 2026-06-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0009_remove_diagnostic_disease_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advicerule',
            name='disease_label',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('apple_scab', 'Apple scab'), ('black_rot', 'Black rot'), ('cedar_apple_rust', 'Cedar apple rust'), ('powdery_mildew', 'Powdery mildew'), ('cercospora_leaf_spot', 'Cercospora leaf spot / Gray leaf spot'), ('common_rust', 'Common rust'), ('northern_leaf_blight', 'Northern leaf blight'), ('esca', 'Esca (Black Measles)'), ('leaf_blight', 'Leaf blight (Isariopsis)'), ('haunglongbing', 'Haunglongbing (Citrus greening)'), ('bacterial_spot', 'Bacterial spot'), ('early_blight', 'Early blight'), ('late_blight', 'Late blight'), ('leaf_mold', 'Leaf mold'), ('septoria_leaf_spot', 'Septoria leaf spot'), ('spider_mites', 'Spider mites'), ('target_spot', 'Target spot'), ('mosaic_virus', 'Mosaic virus'), ('yellow_leaf_curl_virus', 'Yellow leaf curl virus'), ('leaf_scorch', 'Leaf scorch')], max_length=255),
        ),
        migrations.AlterField(
            model_name='advicerule',
            name='plant_type',
            field=models.CharField(blank=True, choices=[('apple', 'Apple'), ('blueberry', 'Blueberry'), ('cherry', 'Cherry'), ('corn', 'Corn'), ('grape', 'Grape'), ('orange', 'Orange'), ('peach', 'Peach'), ('pepper', 'Bell Pepper'), ('potato', 'Potato'), ('raspberry', 'Raspberry'), ('soybean', 'Soybean'), ('squash', 'Squash'), ('strawberry', 'Strawberry'), ('tomato', 'Tomato')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='advicerule',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('clay', 'Clay'), ('sandy', 'Sandy'), ('loamy', 'Loamy'), ('chalky', 'Chalky')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='detected_disease',
            field=models.CharField(blank=True, choices=[('healthy', 'Healthy'), ('apple_scab', 'Apple scab'), ('black_rot', 'Black rot'), ('cedar_apple_rust', 'Cedar apple rust'), ('powdery_mildew', 'Powdery mildew'), ('cercospora_leaf_spot', 'Cercospora leaf spot / Gray leaf spot'), ('common_rust', 'Common rust'), ('northern_leaf_blight', 'Northern leaf blight'), ('esca', 'Esca (Black Measles)'), ('leaf_blight', 'Leaf blight (Isariopsis)'), ('haunglongbing', 'Haunglongbing (Citrus greening)'), ('bacterial_spot', 'Bacterial spot'), ('early_blight', 'Early blight'), ('late_blight', 'Late blight'), ('leaf_mold', 'Leaf mold'), ('septoria_leaf_spot', 'Septoria leaf spot'), ('spider_mites', 'Spider mites'), ('target_spot', 'Target spot'), ('mosaic_virus', 'Mosaic virus'), ('yellow_leaf_curl_virus', 'Yellow leaf curl virus'), ('leaf_scorch', 'Leaf scorch')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='detected_plant',
            field=models.CharField(blank=True, choices=[('apple', 'Apple'), ('blueberry', 'Blueberry'), ('cherry', 'Cherry'), ('corn', 'Corn'), ('grape', 'Grape'), ('orange', 'Orange'), ('peach', 'Peach'), ('pepper', 'Bell Pepper'), ('potato', 'Potato'), ('raspberry', 'Raspberry'), ('soybean', 'Soybean'), ('squash', 'Squash'), ('strawberry', 'Strawberry'), ('tomato', 'Tomato')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plantsubmission',
            name='plant_type',
            field=models.CharField(blank=True, choices=[('apple', 'Apple'), ('blueberry', 'Blueberry'), ('cherry', 'Cherry'), ('corn', 'Corn'), ('grape', 'Grape'), ('orange', 'Orange'), ('peach', 'Peach'), ('pepper', 'Bell Pepper'), ('potato', 'Potato'), ('raspberry', 'Raspberry'), ('soybean', 'Soybean'), ('squash', 'Squash'), ('strawberry', 'Strawberry'), ('tomato', 'Tomato')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plantsubmission',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('clay', 'Clay'), ('sandy', 'Sandy'), ('loamy', 'Loamy'), ('chalky', 'Chalky')], max_length=20, null=True),
        ),
    ]
