# Generated by Django 6.0.6 on 2026-07-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0010_alter_advicerule_disease_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('low_confidence', 'Low confidence'), ('no_advice', 'No advice available'), ('ai_error', 'Ai error')], default='pending', max_length=50),
        ),
    ]
