# Generated by Django 6.0.6 on 2026-07-10 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0011_alter_diagnostic_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostic',
            name='advice_text',
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='advice_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnostics', to='diagnostic.advicerule'),
        ),
    ]
