# Generated by Django 6.0.6 on 2026-07-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0012_remove_diagnostic_advice_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, choices=[('watering', 'Watering'), ('fungicide', 'Fungicide'), ('pruning', 'Pruning'), ('soil', 'Soil'), ('sunlight', 'Sunlight')], max_length=50, null=True)),
                ('title_en', models.CharField(max_length=255)),
                ('title_fr', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('description_fr', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='advicerule',
            name='treatments',
            field=models.ManyToManyField(blank=True, related_name='advice_rules', to='diagnostic.treatment'),
        ),
    ]
