# Generated by Django 6.0.6 on 2026-07-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0013_treatment_advicerule_treatments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advicerule',
            old_name='advice_text',
            new_name='advice_text_en',
        ),
        migrations.AddField(
            model_name='advicerule',
            name='advice_text_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='description_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='title_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
