services:
  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - greencheck-frontend-nw
    restart: unless-stopped

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    environment:
      - DEBUG=True
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./backend:/app:ro
    depends_on:
      db:
        condition: service_healthy
    networks:
      - greencheck-frontend-nw
      - greencheck-backend-nw
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    networks:
      - greencheck-backend-nw
    restart: always
    

  worker:
    build: ./backend
    command: celery -A config worker --loglevel=info
    env_file:
      - .env
    volumes:
      - ./backend:/app:ro
    depends_on:
      - redis
      - ai-service
    networks:
      - greencheck-backend-nw
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - greencheck-backend-nw
    restart: unless-stopped

  ai-service:
    build: ./ai-service
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./ai-service:/app:ro
    depends_on:
      - backend
    networks:
      - greencheck-backend-nw
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: greencheck-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    read-only: true
    depends_on:
      - frontend
      - backend
    networks:
      - reverse-proxy-nw
      - greencheck-frontend-nw

volumes:
  db_data:

networks:
  reverse-proxy-nw:
    external: true
  greencheck-backend-nw:
    internal: true
  greencheck-frontend-nw:
    internal: true
