from diagnostic.models import PlantTypeChoice, DiseaseLabelChoice

CLASS_NAME_MAP = {
    "Apple__Apple_scab":                                    (PlantTypeChoice.APPLE,       DiseaseLabelChoice.APPLE_SCAB),
    "Apple__Black_rot":                                     (PlantTypeChoice.APPLE,       DiseaseLabelChoice.BLACK_ROT),
    "Apple__Cedar_apple_rust":                              (PlantTypeChoice.APPLE,       DiseaseLabelChoice.CEDAR_APPLE_RUST),
    "Apple__healthy":                                       (PlantTypeChoice.APPLE,       DiseaseLabelChoice.HEALTHY),
    "Blueberry__healthy":                                   (PlantTypeChoice.BLUEBERRY,   DiseaseLabelChoice.HEALTHY),
    "Cherry__healthy":                                      (PlantTypeChoice.CHERRY,      DiseaseLabelChoice.HEALTHY),
    "Cherry__Powdery_mildew":                               (PlantTypeChoice.CHERRY,      DiseaseLabelChoice.POWDERY_MILDEW),
    "Corn__Cercospora_leaf_spot Gray_leaf_spot":            (PlantTypeChoice.CORN,        DiseaseLabelChoice.CERCOSPORA_LEAF_SPOT),
    "Corn__Common_rust_":                                   (PlantTypeChoice.CORN,        DiseaseLabelChoice.COMMON_RUST),
    "Corn__healthy":                                        (PlantTypeChoice.CORN,        DiseaseLabelChoice.HEALTHY),
    "Corn__Northern_Leaf_Blight":                           (PlantTypeChoice.CORN,        DiseaseLabelChoice.NORTHERN_LEAF_BLIGHT),
    "Grape__Black_rot":                                     (PlantTypeChoice.GRAPE,       DiseaseLabelChoice.BLACK_ROT),
    "Grape__Esca_(Black_Measles)":                          (PlantTypeChoice.GRAPE,       DiseaseLabelChoice.ESCA),
    "Grape__healthy":                                       (PlantTypeChoice.GRAPE,       DiseaseLabelChoice.HEALTHY),
    "Grape__Leaf_blight_(Isariopsis_Leaf_Spot":             (PlantTypeChoice.GRAPE,       DiseaseLabelChoice.LEAF_BLIGHT),
    "Orange__Haunglongbing_(Citrus_greening)":              (PlantTypeChoice.ORANGE,      DiseaseLabelChoice.HAUNGLONGBING),
    "Peach__Bacterial_spot":                                (PlantTypeChoice.PEACH,       DiseaseLabelChoice.BACTERIAL_SPOT),
    "Peach__healthy":                                       (PlantTypeChoice.PEACH,       DiseaseLabelChoice.HEALTHY),
    "Pepper,_bell__Bacterial_spot":                         (PlantTypeChoice.PEPPER,      DiseaseLabelChoice.BACTERIAL_SPOT),
    "Pepper,_bell__healthy":                                (PlantTypeChoice.PEPPER,      DiseaseLabelChoice.HEALTHY),
    "Potato__Early_blight":                                 (PlantTypeChoice.POTATO,      DiseaseLabelChoice.EARLY_BLIGHT),
    "Potato__healthy":                                      (PlantTypeChoice.POTATO,      DiseaseLabelChoice.HEALTHY),
    "Potato__Late_blight":                                  (PlantTypeChoice.POTATO,      DiseaseLabelChoice.LATE_BLIGHT),
    "Raspberry__healthy":                                   (PlantTypeChoice.RASPBERRY,   DiseaseLabelChoice.HEALTHY),
    "Soybean__healthy":                                     (PlantTypeChoice.SOYBEAN,     DiseaseLabelChoice.HEALTHY),
    "Squash__Powdery_mildew":                               (PlantTypeChoice.SQUASH,      DiseaseLabelChoice.POWDERY_MILDEW),
    "Strawberry__healthy":                                  (PlantTypeChoice.STRAWBERRY,  DiseaseLabelChoice.HEALTHY),
    "Strawberry__Leaf_scorch":                              (PlantTypeChoice.STRAWBERRY,  DiseaseLabelChoice.LEAF_SCORCH),
    "Tomato__Bacterial_spot":                               (PlantTypeChoice.TOMATO,      DiseaseLabelChoice.BACTERIAL_SPOT),
    "Tomato__Early_blight":                                 (PlantTypeChoice.TOMATO,      DiseaseLabelChoice.EARLY_BLIGHT),
    "Tomato__healthy":                                      (PlantTypeChoice.TOMATO,      DiseaseLabelChoice.HEALTHY),
    "Tomato__Late_blight":                                  (PlantTypeChoice.TOMATO,      DiseaseLabelChoice.LATE_BLIGHT),
    "Tomato__Leaf_Mold":                                    (PlantTypeChoice.TOMATO,      DiseaseLabelChoice.LEAF_MOLD),
    "Tomato__Septoria_leaf_spot":                           (PlantTypeChoice.TOMATO,      DiseaseLabelChoice.SEPTORIA_LEAF_SPOT),
    "Tomato__Spider_mites Two-spotted_spider_mite":         (PlantTypeChoice.TOMATO,      DiseaseLabelChoice.SPIDER_MITES),
    "Tomato__Target_Spot":                                  (PlantTypeChoice.TOMATO,      DiseaseLabelChoice.TARGET_SPOT),
    "Tomato__Tomato_mosaic_virus":                          (PlantTypeChoice.TOMATO,      DiseaseLabelChoice.MOSAIC_VIRUS),
    "Tomato__Tomato_Yellow_Leaf_Curl_Virus":                (PlantTypeChoice.TOMATO,      DiseaseLabelChoice.YELLOW_LEAF_CURL_VIRUS),
}
