export { default as Advice } from "./Advice"
export { default as DiseaseResult } from "./DiseaseResult"
export { default as HealthyResult, type BaseResultProps  } from "./HealthyResult"
export { default as SeverityLabel } from "./SeverityLabel"
export { default as StatusTicker } from "./StatusTicker"
export { default as Treatments } from "./Treatments"
